In [87]:
import numpy as np
import matplotlib.pyplot as plt

# 7.

In [88]:
u1 = np.array([3.,1.,0.,1.,])
u2 = np.array([1.,2.,1.,1.,])
u3 = np.array([-1.,0.,2.,-1.,])
b = np.array([-3.,-3.,8.,9.])

A = np.array([u1,u2,u3]).T
A

array([[ 3.,  1., -1.],
       [ 1.,  2.,  0.],
       [ 0.,  1.,  2.],
       [ 1.,  1., -1.]])

a)

In [89]:
AT = np.dot(A.T,A)
bT = np.dot(A.T,b)
xsol = np.linalg.solve(AT,bT)
np.dot(A,xsol)

array([-2.00000000e+00,  3.00000000e+00,  4.00000000e+00,  1.11022302e-16])

b)

In [90]:
def Gram_Schmidt (W):

    P = np.zeros(shape=np.shape(W))
    P[0] = W[0]/np.linalg.norm(W[0])

    for i in range(1,np.shape(W)[0]):
        sum = np.zeros(shape=np.shape(W)[1])
        for j in range(0,i):
            sum += (np.dot(W[i],P[j])/np.dot(P[j],P[j]))*P[j]
        P[i] = W[i] - sum
        P[i] = P[i]/np.linalg.norm(P[i])
    return P

O = Gram_Schmidt(A.T)
O

array([[ 0.90453403,  0.30151134,  0.        ,  0.30151134],
       [-0.32961713,  0.75341057,  0.51796977,  0.2354408 ],
       [ 0.25633581, -0.26982716,  0.78249877, -0.49918025]])

In [91]:
P = np.zeros(shape=np.shape(O)[1])
for i in O:
    P += np.dot(b,i)*i
P

array([-2.00000000e+00,  3.00000000e+00,  4.00000000e+00,  5.55111512e-16])