In [1]:
import numpy as np

In [2]:
def mulM(A,B):

    if len(np.shape(A)) == 1:
        A = np.reshape(A,(1,len(A)))

    if len(np.shape(B)) == 1:
        B = np.reshape(B,(len(B),1))

    AB = np.zeros(shape=(np.shape(A)[0],np.shape(B)[1]))

    if np.shape(A)[1] == np.shape(B)[0]:
        for i in range(np.shape(B)[1]):
            for j in range(np.shape(A)[0]):
                suma = 0
                for k in range(np.shape(A)[1]):
                    suma += A[j][k]*B[k][i]
                AB[j][i] = suma
    else:
        AB = None
        print('Multiplicación no está definida')
    
    return AB

In [3]:
A = np.array([[1.,0.,0.],
             [5.,1.,0.],
             [-2.,3.,1.]])

B = np.array([[4.,-2.,1.],
             [0.,3.,7.],
             [0.,0.,2.]])

M = mulM(A,B)
#M_ = np.matmul(A,B)
print(M)
#print(M_)

[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
